### ISSUE TITLE
error : The 'Publish' target is not supported without specifying a target framework.

### ISSUE THREAD

**Issue by lavilaso** [inclusive-thinking/photo-labeler#13]
Estoy obteniendo el siguiente error al tratar de ejecutar electronize start:

C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.CrossTargeting.targets(27,5): error : The 'Publish' target is not supported without specifying a target framework. The current project targets multiple frameworks, please specify the framework for the published application. [C:\Users\lavilaso\source\repos\photo-labeler\metadata-extractor\MetadataExtractor\MetadataExtractor.csproj]

Luego al final del todo:
Error occurred during dotnet publish: 1

Alguna idea de como solucionarlo ?

**Comment by kastwey** [comment]
Hi,

It seems like you are executing electronize start inside root repository folder in stead of src/PhotoLabeler subfolder.
Go to C:\Users\lavilaso\source\repos\photo-labeler\src/PhotoLabeler and try again.

Thanks!

**Comment by lavilaso** [comment]
Gracias, mi tonto error.
